config:
  target: "http://local.tre.se:3000/support"
  tls:
    "rejectUnauthorized": false

  phases:
    - duration: 60
      arrivalRate: 5

scenarios:
  - flow:
      - get:
          url: "http://local.tre.se:3000/support"
      #- get:
      #    url: "https://web.bt1.tre.se/"
