config:
  target: "https://stage.webtest.tre.se/support"

  phases:
    - duration: 60
      arrivalRate: 10
      rampTo: 20
    # - duration: 60
    #   arrivalRate: 10
    #   rampTo: 30
scenarios:
  - flow:
      - get:
          url: "https://stage.webtest.tre.se/support"
      # - think: 3
      # - get:
      #     url: "https://172.29.11.254/"
