config:
  target: "http://localhost:3000/support"
  tls:
    "rejectUnauthorized": false

  phases:
    - duration: 120
      arrivalRate: 1

scenarios:
  - flow:
      - get:
          url: "http://localhost:3000/support"
      #- get:
      #    url: "https://web.bt1.tre.se/"
